/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'mak' at '11/6/17 7:05 PM' with Gradle 2.14.1
 *
 * @author mak, @date 11/6/17 7:05 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
